;5.20.. DE DOS NUMEROS EN HEXADESIMAL 	A  BCD 7 SEGMENTOS
	ORG $0000
DATO		rmb	1
RESULTADO	rmb	2

	ORG $8000
inicio	LDX	#tabla
	LDAB	DATO
	LSRB
	LSRB
	LSRB			;ROTO PARA LA DERECHA(DE MAS SIGNIF A MENOS) PARA QUE ME QUEDE LA PARTE ALTA ABAJO.
	LSRB
	ABX
	LDAA	0,X		;CARGO EN A LA PARTE ALTA.
	LDX	#tabla
	LDAB	DATO
	ANDB	#$0F
	ABX
	LDAB	0,X
	STD	RESULTADO	;GUARDO LOS 16 BITS DE RESULTADO
FIN	BRA	FIN
	

	ORG dato
	db $78


tabla
	db $3f,$06,$5b,$4f,$66,$6d,$7d,$07,$7f,$6f

	ORG $fffe
	dw inicio
